# Generated by Django 5.2.7 on 2025-10-23 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='metrics',
            field=models.ManyToManyField(blank=True, to='analytics.analyticsmetric'),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='recipients',
            field=models.ManyToManyField(related_name='report_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsdata',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='analytics.analyticssource'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='dashboards',
            field=models.ManyToManyField(blank=True, to='analytics.dashboard'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='metrics',
            field=models.ManyToManyField(related_name='widgets', to='analytics.analyticsmetric'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='widgets', to='analytics.analyticssource'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analyticsdata',
            index=models.Index(fields=['source', 'metric', 'date'], name='analytics_d_source__bc9f16_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdata',
            index=models.Index(fields=['date'], name='analytics_d_date_7c43aa_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type', 'created_at'], name='user_activi_user_id_de49e5_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['created_at'], name='user_activi_created_9fa3ca_idx'),
        ),
    ]
