# Generated by Django 4.2.7 on 2025-10-23 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_fix_duplicate_created_by"),
        ("analytics", "0002_initial"),
    ]

    operations = []
