# Generated by Django 5.2.7 on 2025-10-23 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeed',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityfeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='focus_skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.AddField(
            model_name='communitygroup',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='community.communitygroup'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='connection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship', to='community.connection'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorship_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='skills_focus',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.AddField(
            model_name='mentorshipsession',
            name='mentorship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='community.mentorship'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='community.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
