# Generated by Django 5.2.7 on 2025-10-23 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outvier', '0001_initial'),
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outvier_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddField(
            model_name='goal',
            name='related_skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outvier_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.goal'),
        ),
        migrations.AddField(
            model_name='goalmilestone',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='outvier.goal'),
        ),
        migrations.AddField(
            model_name='growthpathway',
            name='recommended_projects',
            field=models.ManyToManyField(blank=True, to='projects.project'),
        ),
        migrations.AddField(
            model_name='growthpathway',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.AddField(
            model_name='growthpathway',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outvier_pathways', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goal',
            name='related_pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.growthpathway'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='related_pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.growthpathway'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learningstreak',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streaks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.achievement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.goal'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.growthpathway'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outvier_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationschedule',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outvier.goal'),
        ),
        migrations.AddField(
            model_name='notificationschedule',
            name='related_pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outvier.growthpathway'),
        ),
        migrations.AddField(
            model_name='notificationschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pathwaystep',
            name='pathway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='outvier.growthpathway'),
        ),
        migrations.AddField(
            model_name='pathwaystep',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='outvier.pathwaystep'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='pathway_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='outvier.pathwaystep'),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outvier_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressinsight',
            name='related_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.goal'),
        ),
        migrations.AddField(
            model_name='progressinsight',
            name='related_pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.growthpathway'),
        ),
        migrations.AddField(
            model_name='progressinsight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outvier_insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='matched_users',
            field=models.ManyToManyField(blank=True, related_name='matched_with', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='project_categories',
            field=models.ManyToManyField(blank=True, to='projects.projectcategory'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='users.skill'),
        ),
        migrations.AddField(
            model_name='teammatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outvier_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progressinsight',
            name='related_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.teammatch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outvier.teammatch'),
        ),
        migrations.AlterUniqueTogether(
            name='pathwaystep',
            unique_together={('pathway', 'step_number')},
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('user', 'pathway_step')},
        ),
    ]
