# Generated by Django 4.2.7 on 2025-10-23 03:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outvier", "0002_initial"),
        ("outvier", "0003_teammatch_is_public"),
    ]

    operations = []
